### ISSUE TITLE
App tutorial

### ISSUE THREAD

**Issue by meagrivera** [OpenGridMap/OpenGridMapApp#11]
we need to introduce what is to do tith the app.
Please come up with a concept. Try to mimic the animations of cartons other apps use.

**Comment by meagrivera** [comment]
I actually think this is not necessary...I think the app is simple enough.....what do you think?

**Comment by tanujghinaiya** [comment]
A simple introduction would help users understand the goal of the project and the purpose of the app itself. Also since the intro runs only once, it does not affect the interactions later. So it would help users in understanding what they have to do with the app and the purpose behind it.

The implementation is already complete, so no additional work is required since the associated bugs are now fixed.
